config/routes.rb
Minijobs::Application.routes.draw do
  devise_for :adults
  devise_for :kids

  root to: "content#index"

  get 'me' => 'content#dashboard'
  get 'profile' => 'content#profile'

  resources :adults
  resources :kids
  resources :jobs do
    member do
      get 'apply' => 'jobs#apply_for_job'
      get 'application' => 'jobs#accept_job'
      get 'accept/:kid_id' => 'jobs#accept_application'
    end
  end


end

app/models/kid.rb
class Kid < ActiveRecord::Base
  scope :created_today, -> { where('created_at > ?', Date.today.beginning_of_day) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :username
  attr_accessible :name

  belongs_to :adult
  has_many :jobs, :through => :adult

  def lat_long
    [adult.latitude, adult.longitude]
  end

  def parent
    adult
  end

  def jobs
    parent.jobs
  end

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kids }
    end
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
    @kid = Kid.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kid }
    end
  end

  # GET /kids/new
  # GET /kids/new.json
  def new
    @kid = Kid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/1/edit
  def edit
    @kid = Kid.find(params[:id])
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(params[:kid])

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render json: @kid, status: :created, location: @kid }
      else
        format.html { render action: "new" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kids/1
  # PUT /kids/1.json
  def update
    @kid = Kid.find(params[:id])

    respond_to do |format|
      if @kid.update_attributes(params[:kid])
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy

    respond_to do |format|
      format.html { redirect_to kids_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/dashboard.html.erb
          <div id="main">
                <div id="dashboard">
                   <% current_kid.jobs.each do |job| %>
                  <div id="summary">
                      <img class="summary_img" src="app/assets/images/dashboard-seeker-profile.png">
                        <h1>SUMMARY</h1>
                        <div id="pending">
                          <img src="app/assets/images/dashboard-icon-completed.png">
                            <h2>Pending</h2>
                            <p>2 jobs to be approved</p>
                        </div>
                        <div id="completed">
                          <img src="app/assets/images/dashboard-icon-approved.png">
                            <h2>Completed</h2>
                            <p>2 jobs completed</p>
                        </div>
                        <div id="progress">
                          <img src="app/assets/images/dashboard-icon-inprogress.png">
                            <h2>In Progress</h2>
                            <p>3 upcoming jobs</p>
                        </div>

                    </div>
                    <div class="dashboard_listing">
                      <img class="job_img" src="img/jobs-profile1.png">
                        <div class="job_post">
                          <h3 class="job_lister"><%= job.listername %></h3>
                            <h2 class="job_name"><%= job.name %></h2>


                            <div class="job_details">
                              <div class="job_distance">
                                  <img src="img/jobs-icon-location.png">
                                  <h4>10 mins</h4>
                                    <p>Walking Distance</p>
                                </div>
                                <div class="job_price">
                                  <img src="img/jobs-icon-coin.png">
                                  <h4>$30</h4>
                                    <p>Once a week</p>
                                </div>
                            </div>
                            <div class="job_description">
                              <h5>DESCRIPTION</h5>
                                <p>Description of job Description of job Description of job Description of job Description of job</p>
                            </div>
                            <div class="job_status">
                                <img src="app/assets/images/dashboard-icon-approved.png">
                                <h2>Completed</h2>
                                <p>On 25/02/2014</p>
                            </div>
                        </div>
                      </div>

                      <div class="dashboard_listing">
                      <img class="job_img" src="img/jobs-profile2.png">
                        <div class="job_post">
                          <h3 class="job_lister">Job Lister</h3>
                            <h2 class="job_name">Job Name</h2>
                            <div class="job_details">
                              <div class="job_distance">
                                  <img src="img/jobs-icon-location.png">
                                  <h4>10 mins</h4>
                                    <p>Walking Distance</p>
                                </div>
                                <div class="job_price">
                                  <img src="img/jobs-icon-coin.png">
                                  <h4>$30</h4>
                                    <p>Once a week</p>
                                </div>
                            </div>
                            <div class="job_description">
                              <h5>DESCRIPTION</h5>
                                <p>Description of job Description of job Description of job Description of job Description of job</p>
                            </div>
                            <div class="job_status">
                                <img src="app/assets/images/dashboard-icon-completed.png">
                                <h2>pending</h2>
                                <p>confirmation needed</p>
                            </div>
                        </div>
                        </div>

                      <div class="dashboard_listing">
                      <img class="job_img" src="img/jobs-profile3.png">
                        <div class="job_post">
                          <h3 class="job_lister">Job Lister</h3>
                            <h2 class="job_name">Job Name</h2>


                            <div class="job_details">
                              <div class="job_distance">
                                  <img src="img/jobs-icon-location.png">
                                  <h4>10 mins</h4>
                                    <p>Walking Distance</p>
                                </div>
                                <div class="job_price">
                                  <img src="img/jobs-icon-coin.png">
                                  <h4>$30</h4>
                                    <p>Once a week</p>
                                </div>
                            </div>
                            <div class="job_description">
                              <h5>DESCRIPTION</h5>
                                <p>Description of job Description of job Description of job Description of job Description of job</p>
                            </div>
                            <div class="job_status">
                                <img src="app/assets/images/dashboard-icon-approved.png">
                                <h2>Completed</h2>
                                <p>On 28/02/2014</p>
                            </div>
                            </div>
                      </div>
                </div>
  <% end %>
</div>

app/views/kids/edit.html.erb
<h1>Editing kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<h1>Listing kids</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kids.each do |kid| %>
  <tr>
    <td><%= kid.name %></td>
    <td><%= link_to 'Show', kid %></td>
    <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
    <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/profile.html.erb
<p>
  <b>Name:</b>
  <%= @kid.name %>
</p>


<p> ABOUT ME </p>

app/views/kids/show.html.erb
<p>
  <b>Name:</b>
  <%= @kid.name %>
</p>


<p> ABOUT ME </p>