config/routes.rb
Minijobs::Application.routes.draw do
  devise_for :adults
  devise_for :kids

  root to: "content#index"

  get 'me' => 'content#dashboard'
  get 'profile' => 'content#profile'

  resources :adults
  resources :kids
  resources :jobs do
    member do
      get 'apply' => 'jobs#apply_for_job'
      get 'application' => 'jobs#accept_job'
      get 'accept/:kid_id' => 'jobs#accept_application'
    end
  end


end

app/models/adult.rb
class Adult < ActiveRecord::Base
  scope :all_parents, -> { where(role: 'parent') }
  scope :all_listers, -> { where(role: 'lister') }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :address, :email, :latitude, :longitude, :name

  has_and_belongs_to_many :jobs
  has_many :kids

  geocoded_by :address   # can also be an IP address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def parent?
    role == 'parent'
  end

  def lister?
    role == 'lister'
  end

  def kid
    kids.first
  end
end

app/controllers/adults_controller.rb
class AdultsController < ApplicationController
  # GET /adults
  # GET /adults.json
  def index
    @adults = Adult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adults }
    end
  end

  # GET /adults/1
  # GET /adults/1.json
  def show
    @adult = Adult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @adult }
    end
  end

  # GET /adults/new
  # GET /adults/new.json
  def new
    @adult = Adult.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @adult }
    end
  end

  # GET /adults/1/edit
  def edit
    @adult = Adult.find(params[:id])
  end

  # POST /adults
  # POST /adults.json
  def create
    @adult = Adult.new(params[:adult])

    respond_to do |format|
      if @adult.save
        format.html { redirect_to @adult, notice: 'Adult was successfully created.' }
        format.json { render json: @adult, status: :created, location: @adult }
      else
        format.html { render action: "new" }
        format.json { render json: @adult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adults/1
  # PUT /adults/1.json
  def update
    @adult = Adult.find(params[:id])

    respond_to do |format|
      if @adult.update_attributes(params[:adult])
        format.html { redirect_to @adult, notice: 'Adult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @adult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adults/1
  # DELETE /adults/1.json
  def destroy
    @adult = Adult.find(params[:id])
    @adult.destroy

    respond_to do |format|
      format.html { redirect_to adults_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/adults_helper.rb
module AdultsHelper
end

app/views/adults/_form.html.erb
<%= form_for(@adult) do |f| %>
  <% if @adult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adult.errors.count, "error") %> prohibited this adult from being saved:</h2>

      <ul>
      <% @adult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adults/edit.html.erb
<h1>Editing adult</h1>

<%= render 'form' %>

<%= link_to 'Show', @adult %> |
<%= link_to 'Back', adults_path %>

app/views/adults/index.html.erb
<h1>Listing adults</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adults.each do |adult| %>
  <tr>
    <td><%= adult.name %></td>
    <td><%= adult.email %></td>
    <td><%= adult.address %></td>
    <td><%= adult.latitude %></td>
    <td><%= adult.longitude %></td>
    <td><%= link_to 'Show', adult %></td>
    <td><%= link_to 'Edit', edit_adult_path(adult) %></td>
    <td><%= link_to 'Destroy', adult, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adult', new_adult_path %>

app/views/adults/lister_dashboard.html.erb
<% current_user.jobs.uniq.each do |job| %>
  <% job.kids.each do |kid| %>
    <div class="applicant_listing">
      <img class="application_img">
      <h2 class="job_name"><%= job.name %></h2>
      <h3 class="applicant_name"><%= kid.name %></h3>
      <p class="applicant_description"><%= kid.about %></p>
      <button class="applicant_accept">Accept</button> <!--accept kid to do job-->
    </div>
  <% end %>
<% end %>

app/views/adults/new.html.erb
<h1>New adult</h1>

<%= render 'form' %>

<%= link_to 'Back', adults_path %>

app/views/adults/parent_dashboard.html.erb
<% current_user.jobs.uniq.each do |job| %>
  <div class="applied_listing">
    <img class="job_img">
        <h2 class="job_name"><%= job.name %></h2>
        <h3 class="job_lister"><%= job.lister.name %></h3>
        <h4 class="job_distance"><%= job.distance %></h4>
        <p class="job_description"><%= job.description %></p>
      <h5 class="job_price"><%= job.cost %></h5>
      <% if job.kid_applied? %>
        <%= button_to "Accept", application_job_path(job), class: "applied_accept", method: :get %>
      <% elsif job.parent_accepted? %>
        <p> Waiting for feedback </p>
      <% end %>
  </div>
<% end %>

app/views/adults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @adult.name %>
</p>

<p>
  <b>Email:</b>
  <%= @adult.email %>
</p>

<p>
  <b>Address:</b>
  <%= @adult.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @adult.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @adult.longitude %>
</p>


<%= link_to 'Edit', edit_adult_path(@adult) %> |
<%= link_to 'Back', adults_path %>