config/routes.rb
Minijobs::Application.routes.draw do
  devise_for :adults
  devise_for :kids

  root to: "content#index"

  get 'me' => 'content#dashboard'
  get 'profile' => 'content#profile'

  resources :adults
  resources :kids
  resources :jobs do
    member do
      get 'apply' => 'jobs#apply_for_job'
      get 'application' => 'jobs#accept_job'
      get 'accept/:kid_id' => 'jobs#accept_application'
    end
  end


end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :cost, :description, :duration, :image, :name

  has_and_belongs_to_many :adults

  has_many :kids, :through => :adult

  def lister
    adults.all_listers.first
  end

  def parent
    adults.all_parents.first
  end

  def kids
    parent.present? ? [parent.kid] : []
  end

  def kid_applied?
    status == 'applied'
  end

  def parent_accepted?
    status == 'parent accepted'
  end

  def application_accepted?
    status == 'application accepted'
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :require_adult, except: [:show]
  before_filter :require_kid, only: [:show]

  # FOR KIDS
  def apply_for_job
    job = Job.find(params[:id])
    job.status = 'applied'
    job.save
    current_user.jobs << job
    redirect_to me_path
    # JobMailer.job_applied_email(current_user, job)
  end

  # FOR PARENTS
  def accept_job
    # verify token...
    job = Job.find(params[:id])
    job.status = 'parent accepted'
    job.save
    redirect_to me_path
    # JobMailer.job_parent_accepted_email(current_user, job)
  end

  # FOR LISTERS
  def accept_application
    job = Job.find(params[:id])
    kid = Kid.find(params[:kid_id])
    job.status = 'application accepted'
    job.save
    redirect_to me_path
    # JobMailer.job_lister_accepted_email(current_user, kid, job)
  end

  # GET /jobs
  # GET /jobs.json
  # FOR KIDS
  def index
    @distance = 3
    listers = Adult.near(current_user.lat_long, @distance, units: :km)
    @jobs = listers.map(&:jobs).flatten.uniq

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @job.status = 'listed'

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
  def require_adult
    current_user.is_a? Adult
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Job List</h3>
<% @jobs.uniq.each do |job| %>
  <div class="job_listing">
      <div class="job_post">
        <img class="job_img">
        <div class="job_details">
            <h2 class="job_name"><%= job.name %></h2>
            <h3 class="job_lister"><%= job.lister.name %></h3>
            <h4 class="job_distance"><%= job.distance %> min away</h4>
            <p class="job_description"><%= job.description %></p>
        </div>
        <%= button_to "Apply", apply_job_path(job), class: "job_apply", method: :get %>
        <h5 class="job_price"><%= job.cost %></h5>
      </div>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @job.name %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>

<p>
  <b>Duration:</b>
  <%= @job.duration %>
</p>

<p>
  <b>Cost:</b>
  <%= @job.cost %>
</p>

<p>
  <b>Image:</b>
  <%= @job.image %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

<h1>Job List</h3>
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
  <div class="job_listing">
    <div class="job_post">
      <img class="job_img">
      <div class="job_details">
          <h2 class="job_name">Job Name</h2>
          <h3 class="job_lister">Job Lister</h3>
          <h4 class="job_distance">Job Distance</h4>
          <p class="job_description">Job Description</p>
      </div>
      <button class="job_apply">Apply</button> <!--call pop up-->
      <h5 class="job_price">Job Price</h5>
    </div>
  </div>