config/routes.rb
Minijobs::Application.routes.draw do
  devise_for :adults
  devise_for :kids

  root to: "content#index"

  get 'me' => 'content#dashboard'
  get 'profile' => 'content#profile'

  resources :adults
  resources :kids
  resources :jobs do
    member do
      get 'apply' => 'jobs#apply_for_job'
      get 'application' => 'jobs#accept_job'
      get 'accept/:kid_id' => 'jobs#accept_application'
    end
  end


end

app/views/layouts/_header.html.erb
<div id="wrapper">
  <div id="header">
    <%= link_to image_tag("home-mini-jobs-logo.png") %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="nav">
<!--   < %= link_to image_tag("home-seeker.png"), new_kid_session_path, :id "job_seeker" %> -->
  <%= link_to image_tag("img/nav-profile.png"), profile_path %>
  <%= link_to image_tag("nav-home.png"), me_path %>
  <%= link_to image_tag("nav-jobs.png"), jobs_path %>
  <%= link_to 'kid Sign out', "/kids/sign_out", :method => :delete %>
  <%= link_to 'adult Sign out', "/adults/sign_out", :method => :delete %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MiniJobs</title>
    <meta name="description" content="Small Jobs for Small People">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= javascript_include_tag "application" %>
     <script src="js/vendor/modernizr-2.6.2.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: 'layouts/navbar' if current_user.present? %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


  <%= yield %>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
  <script src="js/plugins.js"></script>
  <script src="js/main.js"></script>

  <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
  <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
  </script>
  </body>

</html>